name: Build, Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  install-node:
    name: Install Node 18 and packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: yarn lint

  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: yarn test:unit

  test-fork:
    name: Test Fork
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore node_modules
        uses: OffchainLabs/actions/node-modules/restore@main

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: ETH_FORK_URL=${{ secrets.ETH_FORK_URL }} ARB_FORK_URL=${{ secrets.ARB_FORK_URL }} yarn test:fork

  test-contract-size:
    name: Test Contract Size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: yarn test:sizes

  test-gas-check:
    name: Test Gas Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: yarn test:gas-check

  test-sigs:
    name: Test Signatures
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: forge build

      - run: yarn test:sigs

  test-storage:
    name: Test Storage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge install

      - run: forge build

      - run: yarn test:storage